import type { CatalogCard } from "@iwsdk-apps/catalog";
import {
  CardDefinition,
  type Cost,
  canonicalJson,
  type Keyword,
  type ManaColor,
  StaticCreatureBonus,
} from "@iwsdk-apps/contracts";

export const STATIC_BONUS_VERSION = "static-bonus-permanent/1";
export const STATIC_BONUS_SOURCE_BUNDLE =
  "6284360d10b959270061e1e0e165cd24a7b16b877bb8b0c70a848114a24355df";
export const STATIC_BONUS_ARCHIVE =
  "ffb464b35a97613efa7927f5c05bdef3b8385b7d82ecf4f50f7487a9ab6c2274";
export const STATIC_BONUS_RULES_HASH =
  "4381ad1b39ab2c05f7d03633a20f711ed37277074d3266dcba5f38cbb527423f";
export const STATIC_BONUS_RESEARCH_HASH =
  "dcfe62f26abbfbfdb35b2cec02e34c50ce2cfc4784f06d451c2929236ecf2e32";
export const STATIC_BONUS_RULES = [
  "109.2",
  "109.5",
  "113.6",
  "117.2b",
  "604.1",
  "604.2",
  "604.7",
  "611.3a",
  "611.3b",
  "611.3c",
  "613.1g",
  "613.4c",
  "613.5",
  "613.7a",
  "613.7d",
  "613.8a",
  "704.3",
  "704.5f",
  "704.5g",
  "903.5c",
] as const;
export interface StaticBonusPermanentSource {
  identity: string;
  sourceVersion: string;
  sourceOrdinal: number;
  rawRecordHash: string;
  name: string;
  oracleText: string;
  manaCost: string;
  cost: Cost;
  manaValue: number;
  typeLine: string;
  types: string[];
  supertypes: string[];
  subtypes: string[];
  colors: ManaColor[];
  colorIdentity: ManaColor[];
  power: number | null;
  toughness: number | null;
  oracleKeywords: string[];
  intrinsicKeywords: Keyword[];
  staticProgram: StaticCreatureBonus;
  commanderEligible: boolean;
  digital: boolean;
  games: string[];
}
/** Forty-one authenticated complete bodies. Source binding is not runtime certification. */
export const STATIC_BONUS_PERMANENTS: readonly StaticBonusPermanentSource[] = [
  {
    identity: "06157e34-dbe1-4936-a718-3b1d70726794",
    sourceVersion: "e66a3c93ee175735f07fd52c99bf267545566591f2c2152456fc77548a02c753",
    sourceOrdinal: 957,
    rawRecordHash: "8f771937ab6af3b1e92f7ab0f9066ac1d6b6d7ef7a20a7adebe1384fff5c45b2",
    name: "Gallows Warden",
    oracleText: "Flying\nOther Spirit creatures you control get +0/+1.",
    manaCost: "{4}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 4,
    },
    manaValue: 5,
    typeLine: "Creature — Spirit",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Spirit"],
    colors: ["W"],
    colorIdentity: ["W"],
    power: 3,
    toughness: 3,
    oracleKeywords: ["Flying"],
    intrinsicKeywords: ["flying"],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Spirit",
      },
      powerDelta: 0,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "0c572396-4e53-4c86-9b04-f41341dcea05",
    sourceVersion: "0f600f7d547c4e9f63ea6f57f9056c9380bf588f7c5c8f91ed8d6724716abf7a",
    sourceOrdinal: 1876,
    rawRecordHash: "fa49295262477d7dabe63881cc66c98d58a8c96bd018806ff0d197b09ee6b486",
    name: "Crucible of Fire",
    oracleText: "Dragon creatures you control get +3/+3.",
    manaCost: "{3}{R}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 1,
      G: 0,
      C: 0,
      generic: 3,
    },
    manaValue: 4,
    typeLine: "Enchantment",
    types: ["Enchantment"],
    supertypes: [],
    subtypes: [],
    colors: ["R"],
    colorIdentity: ["R"],
    power: null,
    toughness: null,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "subtype",
        subtype: "Dragon",
      },
      powerDelta: 3,
      toughnessDelta: 3,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "0d9d7f04-6319-4596-8b74-de5a794936e5",
    sourceVersion: "fbd9211ec7113173ae9662e0be871fb1495fde410ef98ca3f1052df8532208ed",
    sourceOrdinal: 2061,
    rawRecordHash: "7d80a087ae39c2b06f3585635a4473776f98e854a08ae6c035c090f107f2546a",
    name: "Yotian Tactician",
    oracleText: "Other Soldiers you control get +1/+1.",
    manaCost: "{2}{W}{U}",
    cost: {
      W: 1,
      U: 1,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 2,
    },
    manaValue: 4,
    typeLine: "Creature — Human Soldier",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Human", "Soldier"],
    colors: ["U", "W"],
    colorIdentity: ["U", "W"],
    power: 3,
    toughness: 4,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Soldier",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "arena", "mtgo"],
  },
  {
    identity: "15934a19-a29e-4728-816f-20b610eec377",
    sourceVersion: "509f10b1d3857f39d9f2f33fe87149089c28bba8245d8f9f1e215abd2688f3e3",
    sourceOrdinal: 3291,
    rawRecordHash: "a4f867514366312683f920e92da771ce93cdfa05a553d0afb221e105c1876e68",
    name: "Turtle Power!",
    oracleText: "Flash\nTurtles you control get +2/+2.",
    manaCost: "{2}{G}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 0,
      G: 1,
      C: 0,
      generic: 2,
    },
    manaValue: 3,
    typeLine: "Enchantment",
    types: ["Enchantment"],
    supertypes: [],
    subtypes: [],
    colors: ["G"],
    colorIdentity: ["G"],
    power: null,
    toughness: null,
    oracleKeywords: ["Flash"],
    intrinsicKeywords: ["flash"],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "subtype",
        subtype: "Turtle",
      },
      powerDelta: 2,
      toughnessDelta: 2,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "arena", "mtgo"],
  },
  {
    identity: "1b1214e9-1581-4008-b3d4-8b7af6b092fd",
    sourceVersion: "18827665a2d6bb9a67bfc176af9bbfc4d1c1aa57dd574baa2339c570bf57bfa6",
    sourceOrdinal: 4123,
    rawRecordHash: "049d0938b89a7fd2386bb7e63bf3f67d1cfd3c7f25874b9a9d3e19584b6c05cb",
    name: "Veteran Armorer",
    oracleText: "Other creatures you control get +0/+1.",
    manaCost: "{1}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 1,
    },
    manaValue: 2,
    typeLine: "Creature — Human Soldier",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Human", "Soldier"],
    colors: ["W"],
    colorIdentity: ["W"],
    power: 2,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "all",
      },
      powerDelta: 0,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "21e9e1a9-5d6d-473e-adab-6a1e8e2b0ebd",
    sourceVersion: "824b7352841ce4a4299149879ad8f308b6cfd24d7cb9d9443e7f9f1daf10b699",
    sourceOrdinal: 5103,
    rawRecordHash: "93d3c698eaac6ab11bcc2d33ca9d8d2761c3a58b5fe5634335f2159acce9d502",
    name: 'Kongming, "Sleeping Dragon"',
    oracleText: "Other creatures you control get +1/+1.",
    manaCost: "{2}{W}{W}",
    cost: {
      W: 2,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 2,
    },
    manaValue: 4,
    typeLine: "Legendary Creature — Human Advisor",
    types: ["Creature"],
    supertypes: ["Legendary"],
    subtypes: ["Human", "Advisor"],
    colors: ["W"],
    colorIdentity: ["W"],
    power: 2,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "all",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: true,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "2450d35b-7d87-4885-b396-f8e1d3ac0b22",
    sourceVersion: "63ecfcb290f36222b2c439c0ffa47cdd3685ac7e706064adf52aa4a3eb746b76",
    sourceOrdinal: 5454,
    rawRecordHash: "a6af1b3613a0ec51486da7528410ad4689774c10285b1b3fd8becc5bde2dc830",
    name: "Battleground Geist",
    oracleText: "Flying\nOther Spirit creatures you control get +1/+0.",
    manaCost: "{4}{U}",
    cost: {
      W: 0,
      U: 1,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 4,
    },
    manaValue: 5,
    typeLine: "Creature — Spirit",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Spirit"],
    colors: ["U"],
    colorIdentity: ["U"],
    power: 3,
    toughness: 3,
    oracleKeywords: ["Flying"],
    intrinsicKeywords: ["flying"],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Spirit",
      },
      powerDelta: 1,
      toughnessDelta: 0,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "2cc439e8-d112-44e6-bc5a-6e99333c519a",
    sourceVersion: "d25b5b2d0d5b966ef3b48cc8f7dd05ac3ef5c98d9d73a504f6cd225de8ccf899",
    sourceOrdinal: 6660,
    rawRecordHash: "e5ec928a486f37538bbc0a808a9af0221735f7e53aef0db6ad40c92a94cbe992",
    name: "Benalish Marshal",
    oracleText: "Other creatures you control get +1/+1.",
    manaCost: "{W}{W}{W}",
    cost: {
      W: 3,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 0,
    },
    manaValue: 3,
    typeLine: "Creature — Human Knight",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Human", "Knight"],
    colors: ["W"],
    colorIdentity: ["W"],
    power: 3,
    toughness: 3,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "all",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper"],
  },
  {
    identity: "32e4de02-8437-4ffc-acc9-a3736652d282",
    sourceVersion: "9d7c9111ff99acb299ddcb17c1a2a354b1b08a816c059f692b4a8d2e48f8394f",
    sourceOrdinal: 7564,
    rawRecordHash: "c5c37f5c98784cf408591ea2835659ff20522033b16c55a294401bcf97239481",
    name: "Chief of the Scale",
    oracleText: "Other Warrior creatures you control get +0/+1.",
    manaCost: "{W}{B}",
    cost: {
      W: 1,
      U: 0,
      B: 1,
      R: 0,
      G: 0,
      C: 0,
      generic: 0,
    },
    manaValue: 2,
    typeLine: "Creature — Human Warrior",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Human", "Warrior"],
    colors: ["B", "W"],
    colorIdentity: ["B", "W"],
    power: 2,
    toughness: 3,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Warrior",
      },
      powerDelta: 0,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo", "arena"],
  },
  {
    identity: "372f2534-25dc-4ff3-9891-31ee42b33345",
    sourceVersion: "34ccf1c80f8780928c35ed512778f6cd1b88f9316a7cec368e8fea0aaab65a58",
    sourceOrdinal: 8225,
    rawRecordHash: "603304eee67db0feff9288bd8621d78d560112c6662caeb1e5e1da480327f987",
    name: "Kobold Taskmaster",
    oracleText: "Other Kobold creatures you control get +1/+0.",
    manaCost: "{1}{R}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 1,
      G: 0,
      C: 0,
      generic: 1,
    },
    manaValue: 2,
    typeLine: "Creature — Kobold",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Kobold"],
    colors: ["R"],
    colorIdentity: ["R"],
    power: 1,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Kobold",
      },
      powerDelta: 1,
      toughnessDelta: 0,
      layer: "7c",
    },
    commanderEligible: false,
    digital: true,
    games: ["mtgo"],
  },
  {
    identity: "3754dce0-3e97-406f-8807-a4942a222c41",
    sourceVersion: "e80bff9907e9994888fb863238f7096aa51e5759be8babe58ba7f41f2cd44b86",
    sourceOrdinal: 8249,
    rawRecordHash: "7c98399b9237e3a717b087c21a771373526fbc50c44b8fffd8f5fa65e4b2a658",
    name: "Gaea's Anthem",
    oracleText: "Creatures you control get +1/+1.",
    manaCost: "{1}{G}{G}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 0,
      G: 2,
      C: 0,
      generic: 1,
    },
    manaValue: 3,
    typeLine: "Enchantment",
    types: ["Enchantment"],
    supertypes: [],
    subtypes: [],
    colors: ["G"],
    colorIdentity: ["G"],
    power: null,
    toughness: null,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "all",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "52e8ec03-23ed-43a0-bce2-ad0cd5c4d737",
    sourceVersion: "64a180fe4277a75cc23aca5abfcb39d1e60d603c44fac040b33ebe841040a4a8",
    sourceOrdinal: 12446,
    rawRecordHash: "692ec4d31a8febb4f1df6258bef4c2c8f04fd620d0a8e6412a29598a729bd2d6",
    name: "Megantic Sliver",
    oracleText: "Sliver creatures you control get +3/+3.",
    manaCost: "{5}{G}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 0,
      G: 1,
      C: 0,
      generic: 5,
    },
    manaValue: 6,
    typeLine: "Creature — Sliver",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Sliver"],
    colors: ["G"],
    colorIdentity: ["G"],
    power: 3,
    toughness: 3,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "subtype",
        subtype: "Sliver",
      },
      powerDelta: 3,
      toughnessDelta: 3,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "5fa1b2f0-3ba4-49db-9cb5-b6130e4c255e",
    sourceVersion: "8af11b92a052698f87ce069df5a4097201b79dc93cf3858a0027d0f8462727a0",
    sourceOrdinal: 14330,
    rawRecordHash: "d2fdffa6613d217daf7285baf2d9a04128618070b0ef8dc4a7dbab6d50a1bf54",
    name: "Legion Lieutenant",
    oracleText: "Other Vampires you control get +1/+1.",
    manaCost: "{W}{B}",
    cost: {
      W: 1,
      U: 0,
      B: 1,
      R: 0,
      G: 0,
      C: 0,
      generic: 0,
    },
    manaValue: 2,
    typeLine: "Creature — Vampire Knight",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Vampire", "Knight"],
    colors: ["B", "W"],
    colorIdentity: ["B", "W"],
    power: 2,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Vampire",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "63324e72-e580-456a-91be-766c9f07b7b3",
    sourceVersion: "8ed6e10a5f1eea29c6d5d364c8926d74ba03d37213bf39c09cf8f3da63188644",
    sourceOrdinal: 14858,
    rawRecordHash: "48767af89b3aeec4c262571b42e05660cdb4a6185adec349af84596b5cbd623a",
    name: "Kargan Warleader",
    oracleText: "Other Warriors you control get +1/+1.",
    manaCost: "{1}{R}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 1,
      G: 0,
      C: 0,
      generic: 1,
    },
    manaValue: 3,
    typeLine: "Creature — Human Warrior",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Human", "Warrior"],
    colors: ["R", "W"],
    colorIdentity: ["R", "W"],
    power: 3,
    toughness: 3,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Warrior",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["arena", "paper", "mtgo"],
  },
  {
    identity: "636a9364-54a6-4f67-ad96-731646e8bde7",
    sourceVersion: "08861822ebedda5180bbaa24990875616561fd17e7b4eb05aeb4df39ec6317b4",
    sourceOrdinal: 14903,
    rawRecordHash: "9b6f5f3a215aa9f7226cff36d3d66c34a3e3bd72603a3a935360551b08309f9c",
    name: "Chief of the Edge",
    oracleText: "Other Warrior creatures you control get +1/+0.",
    manaCost: "{W}{B}",
    cost: {
      W: 1,
      U: 0,
      B: 1,
      R: 0,
      G: 0,
      C: 0,
      generic: 0,
    },
    manaValue: 2,
    typeLine: "Creature — Human Warrior",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Human", "Warrior"],
    colors: ["B", "W"],
    colorIdentity: ["B", "W"],
    power: 3,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Warrior",
      },
      powerDelta: 1,
      toughnessDelta: 0,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo", "arena"],
  },
  {
    identity: "64247fcb-0e1b-48c9-bdac-769d7edd8d1d",
    sourceVersion: "4f3289d4146c777c1b6de2379c03410e36fb313d34ce56a984a2765919fc3375",
    sourceOrdinal: 15007,
    rawRecordHash: "3e8b44dbe117c0d178eab9aeb723227c97eb4fbf4e7851f79b43acdc10236093",
    name: "Day of Destiny",
    oracleText: "Legendary creatures you control get +2/+2.",
    manaCost: "{3}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 3,
    },
    manaValue: 4,
    typeLine: "Legendary Enchantment",
    types: ["Enchantment"],
    supertypes: ["Legendary"],
    subtypes: [],
    colors: ["W"],
    colorIdentity: ["W"],
    power: null,
    toughness: null,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "legendary",
      },
      powerDelta: 2,
      toughnessDelta: 2,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "6b589e70-9c1d-48dd-a597-479959e692bf",
    sourceVersion: "5e5ad311a4517098fb11ea2bcd3eeeea1e8bd121ebf64c7ebe9c472139caa873",
    sourceOrdinal: 16130,
    rawRecordHash: "0ed657fa0678bb9e1f8d6c821328125c6223311c3ae612b1f51d6ed896ad88b7",
    name: "Predatory Sliver",
    oracleText: "Sliver creatures you control get +1/+1.",
    manaCost: "{1}{G}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 0,
      G: 1,
      C: 0,
      generic: 1,
    },
    manaValue: 2,
    typeLine: "Creature — Sliver",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Sliver"],
    colors: ["G"],
    colorIdentity: ["G"],
    power: 1,
    toughness: 1,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "subtype",
        subtype: "Sliver",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "7f7049e8-49ed-46da-89f7-1e40aefb3b0c",
    sourceVersion: "444f4ecd12639b76bcd8f58f58ed8c4c288aa4cd08830f2a3a7f70f955527bf6",
    sourceOrdinal: 19164,
    rawRecordHash: "4db8eb0fa4d01dbd003fa1739a7cba412fcec564ec1bfe1835fa1f1ca3766ae4",
    name: "Collective Blessing",
    oracleText: "Creatures you control get +3/+3.",
    manaCost: "{3}{G}{G}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 0,
      G: 2,
      C: 0,
      generic: 3,
    },
    manaValue: 6,
    typeLine: "Enchantment",
    types: ["Enchantment"],
    supertypes: [],
    subtypes: [],
    colors: ["G", "W"],
    colorIdentity: ["G", "W"],
    power: null,
    toughness: null,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "all",
      },
      powerDelta: 3,
      toughnessDelta: 3,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "83a76601-ef59-4888-af70-5088dd1f504c",
    sourceVersion: "5c5e17f8ebe7120b90b385ec22fbf33d4c0be647ef8375e178fbb581321fa2f0",
    sourceOrdinal: 19755,
    rawRecordHash: "eb139c18ac78266e6428b108fdbce917e297f97fdea7b3def368e6e646cf31c9",
    name: "Regal Imperiosaur",
    oracleText: "Other Dinosaurs you control get +1/+1.",
    manaCost: "{1}{G}{G}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 0,
      G: 2,
      C: 0,
      generic: 1,
    },
    manaValue: 3,
    typeLine: "Creature — Dinosaur",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Dinosaur"],
    colors: ["G"],
    colorIdentity: ["G"],
    power: 5,
    toughness: 4,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Dinosaur",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "arena", "mtgo"],
  },
  {
    identity: "83e2b251-bd60-4c5c-b9e2-32c22b28fb8b",
    sourceVersion: "2f8547de95bc552eca9ea3572ad60b3b4de1361a5042f92e0d4da955ba5a1fbe",
    sourceOrdinal: 19784,
    rawRecordHash: "613ee18abdbf3bf91896fa3b47b8276c3e9b604021340c90ae2611b9e3a3fc18",
    name: "Pride of the Perfect",
    oracleText: "Elves you control get +2/+0.",
    manaCost: "{3}{B}",
    cost: {
      W: 0,
      U: 0,
      B: 1,
      R: 0,
      G: 0,
      C: 0,
      generic: 3,
    },
    manaValue: 4,
    typeLine: "Enchantment",
    types: ["Enchantment"],
    supertypes: [],
    subtypes: [],
    colors: ["B"],
    colorIdentity: ["B"],
    power: null,
    toughness: null,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "subtype",
        subtype: "Elf",
      },
      powerDelta: 2,
      toughnessDelta: 0,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "8893af49-2f90-4aed-bcaf-905bb9e8ed8f",
    sourceVersion: "3d7e96208d10c20fffa5ce69097f43837fc1fafcf191bcc7289cd434581b9c30",
    sourceOrdinal: 20534,
    rawRecordHash: "0f3afa2bf769138548c8890229f17251584702040af37a9b07c860f6ed4202df",
    name: "Fire Nation's Conquest",
    oracleText: "Creatures you control get +1/+0.",
    manaCost: "{2}{R}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 1,
      G: 0,
      C: 0,
      generic: 2,
    },
    manaValue: 3,
    typeLine: "Enchantment",
    types: ["Enchantment"],
    supertypes: [],
    subtypes: [],
    colors: ["R"],
    colorIdentity: ["R"],
    power: null,
    toughness: null,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "all",
      },
      powerDelta: 1,
      toughnessDelta: 0,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "arena", "mtgo"],
  },
  {
    identity: "96d0e4dd-6cc2-4349-ac44-785b50f8dd90",
    sourceVersion: "983208ee1003447a1276c4027a0a4871054095fd9290ed6bf3f2330e456100b0",
    sourceOrdinal: 22686,
    rawRecordHash: "9b15a6421beb1225d9e7108a26c9964b26b3586702814e3cbca95d058d30877c",
    name: "King of the Pride",
    oracleText: "Other Cats you control get +2/+1.",
    manaCost: "{2}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 2,
    },
    manaValue: 3,
    typeLine: "Creature — Cat",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Cat"],
    colors: ["W"],
    colorIdentity: ["W"],
    power: 2,
    toughness: 1,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Cat",
      },
      powerDelta: 2,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "9b33059c-c862-4452-8609-14a0e2551fb3",
    sourceVersion: "72d9849c0ca26db65a64e4bc81f9d22f6f736136d472a09dc8756902ffa10963",
    sourceOrdinal: 23353,
    rawRecordHash: "20395d2c99397620b581eaeb7c5674f5ecfc50192058139b22f5d3c7462cf3b3",
    name: "Cleaving Sliver",
    oracleText: "Sliver creatures you control get +2/+0.",
    manaCost: "{3}{R}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 1,
      G: 0,
      C: 0,
      generic: 3,
    },
    manaValue: 4,
    typeLine: "Creature — Sliver",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Sliver"],
    colors: ["R"],
    colorIdentity: ["R"],
    power: 2,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "subtype",
        subtype: "Sliver",
      },
      powerDelta: 2,
      toughnessDelta: 0,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "9c5f4d02-eedb-4c6c-9f13-1b7a45382483",
    sourceVersion: "e869f5d523a2ab64d6ad950699731608cdb5fb23096e637c8696928345243d95",
    sourceOrdinal: 23537,
    rawRecordHash: "a68f6ca7c18b735ea97465e088d3a85d503af7a19eaa0b0ba8d319cdc1c48ef7",
    name: "Supreme Phantom",
    oracleText: "Flying\nOther Spirits you control get +1/+1.",
    manaCost: "{1}{U}",
    cost: {
      W: 0,
      U: 1,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 1,
    },
    manaValue: 2,
    typeLine: "Creature — Spirit",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Spirit"],
    colors: ["U"],
    colorIdentity: ["U"],
    power: 1,
    toughness: 3,
    oracleKeywords: ["Flying"],
    intrinsicKeywords: ["flying"],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Spirit",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "aa1a63dd-acb1-465f-8970-667b8d7c57c9",
    sourceVersion: "c5e8ab0f49ea545cc99c0d7229b15774683068a591eb94c4e770ae9039c710d4",
    sourceOrdinal: 25564,
    rawRecordHash: "bdc88b6d4681d1c645271138ace96630077d42ad012d1dcd1f2033aaa5933ef4",
    name: "Inspiring Veteran",
    oracleText: "Other Knights you control get +1/+1.",
    manaCost: "{R}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 1,
      G: 0,
      C: 0,
      generic: 0,
    },
    manaValue: 2,
    typeLine: "Creature — Human Knight",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Human", "Knight"],
    colors: ["R", "W"],
    colorIdentity: ["R", "W"],
    power: 2,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Knight",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["arena", "paper", "mtgo"],
  },
  {
    identity: "ae58e71c-b617-404f-a5dc-5e6a487f2675",
    sourceVersion: "e0840aeb3ed00cb4d233efcfa4db195d88216068cda349e4c8379d2d323208c4",
    sourceOrdinal: 26194,
    rawRecordHash: "d868d2081e8cd7cd0e6c5ece7e8d27f88e7904ecac72288e0c1d2c5336ee21d4",
    name: "Steelform Sliver",
    oracleText: "Sliver creatures you control get +0/+1.",
    manaCost: "{2}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 2,
    },
    manaValue: 3,
    typeLine: "Creature — Sliver",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Sliver"],
    colors: ["W"],
    colorIdentity: ["W"],
    power: 2,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "subtype",
        subtype: "Sliver",
      },
      powerDelta: 0,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "b04ba676-a1f5-4216-9d93-3c475b504bfa",
    sourceVersion: "e189918989dda30b278a85d54429d10a6bb839f0dfb7775cf74467aaef8ec5bb",
    sourceOrdinal: 26506,
    rawRecordHash: "c330fb7c9f5afbb2e35b62acb554b1dc2dce5389c239f47bccb8476d9b56911b",
    name: "Thirsting Bloodlord",
    oracleText: "Other Vampires you control get +1/+1.",
    manaCost: "{2}{B}{B}",
    cost: {
      W: 0,
      U: 0,
      B: 2,
      R: 0,
      G: 0,
      C: 0,
      generic: 2,
    },
    manaValue: 4,
    typeLine: "Creature — Vampire",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Vampire"],
    colors: ["B"],
    colorIdentity: ["B"],
    power: 3,
    toughness: 3,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Vampire",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["arena", "paper", "mtgo"],
  },
  {
    identity: "b5905ef3-6565-462f-a015-2bb5b5b09eff",
    sourceVersion: "c715b6e1f609c5100c509afc498c0b11544d166133a961dfe19c453d4ff3436c",
    sourceOrdinal: 27291,
    rawRecordHash: "5653de8ac3820393d30943fcfb02239b85eea958007ef8ea5847bcac37e73b85",
    name: "Wizened Cenn",
    oracleText: "Other Kithkin creatures you control get +1/+1.",
    manaCost: "{W}{W}",
    cost: {
      W: 2,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 0,
    },
    manaValue: 2,
    typeLine: "Creature — Kithkin Cleric",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Kithkin", "Cleric"],
    colors: ["W"],
    colorIdentity: ["W"],
    power: 2,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Kithkin",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "b989279c-665d-4f15-afc1-adf3872a4851",
    sourceVersion: "bcd0fec8abc2c2e969ea909924ed66a92d3e2b6e7be251119fbac56a874573a0",
    sourceOrdinal: 27869,
    rawRecordHash: "58750c6a1c1fd9e04102741fb4c5cc80a609fee6090025ffe8eda8f982170215",
    name: "Dictate of Heliod",
    oracleText: "Flash\nCreatures you control get +2/+2.",
    manaCost: "{3}{W}{W}",
    cost: {
      W: 2,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 3,
    },
    manaValue: 5,
    typeLine: "Enchantment",
    types: ["Enchantment"],
    supertypes: [],
    subtypes: [],
    colors: ["W"],
    colorIdentity: ["W"],
    power: null,
    toughness: null,
    oracleKeywords: ["Flash"],
    intrinsicKeywords: ["flash"],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "all",
      },
      powerDelta: 2,
      toughnessDelta: 2,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper"],
  },
  {
    identity: "be56dfea-1ece-4f06-b1cc-d7425b5018b4",
    sourceVersion: "6214e69ea518b00498fea14935db6c0bacb46fd8bea11025375afdf8b2f4771c",
    sourceOrdinal: 28603,
    rawRecordHash: "cac69c9f364709ed4e3d1fbf68929aba8c4bf19c6f9a6cb1ee0c1eebacdeafd0",
    name: "Merfolk Mistbinder",
    oracleText: "Other Merfolk you control get +1/+1.",
    manaCost: "{G}{U}",
    cost: {
      W: 0,
      U: 1,
      B: 0,
      R: 0,
      G: 1,
      C: 0,
      generic: 0,
    },
    manaValue: 2,
    typeLine: "Creature — Merfolk Shaman",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Merfolk", "Shaman"],
    colors: ["G", "U"],
    colorIdentity: ["G", "U"],
    power: 2,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Merfolk",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "c0856fea-cbdc-427b-ae00-bfd9311f284f",
    sourceVersion: "cdf9869dedad0762e81b8216eef0496573f65bfff8572b9cc5dd48e949ed3878",
    sourceOrdinal: 28947,
    rawRecordHash: "74d27d502addebfecd71958d26753aef8ae2d7ba2ad0e4a5e1f650732764c8c5",
    name: "Blessed Orator",
    oracleText: "Other creatures you control get +0/+1.",
    manaCost: "{3}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 3,
    },
    manaValue: 4,
    typeLine: "Creature — Human Cleric",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Human", "Cleric"],
    colors: ["W"],
    colorIdentity: ["W"],
    power: 1,
    toughness: 4,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "all",
      },
      powerDelta: 0,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "c55a4b25-ccc4-49de-9f98-a829c547a64d",
    sourceVersion: "5f3a098933b65ab9313754c926bc91fd8a021f46cd208b023d5bfe41ed37bd8f",
    sourceOrdinal: 29672,
    rawRecordHash: "befcb32872dfcd5b1cb87c46ce0a3980b371a672641342e8148afa1c477ac75e",
    name: "White Lotus Reinforcements",
    oracleText: "Vigilance\nOther Allies you control get +1/+1.",
    manaCost: "{1}{G}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 0,
      G: 1,
      C: 0,
      generic: 1,
    },
    manaValue: 3,
    typeLine: "Creature — Human Soldier Ally",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Human", "Soldier", "Ally"],
    colors: ["G", "W"],
    colorIdentity: ["G", "W"],
    power: 2,
    toughness: 3,
    oracleKeywords: ["Vigilance"],
    intrinsicKeywords: ["vigilance"],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Ally",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "arena", "mtgo"],
  },
  {
    identity: "cc71b6c4-09d4-423b-a134-2f2f2fd7b533",
    sourceVersion: "211517e6b886ebcc515de799f58a20170a5fbceadc3792b4911a27305e59f04c",
    sourceOrdinal: 30751,
    rawRecordHash: "01541b2ea423ef26c809a04fadd0d5bae46a72d50ee3ab08ecc5807a9a30ef45",
    name: "Veteran Swordsmith",
    oracleText: "Other Soldier creatures you control get +1/+0.",
    manaCost: "{2}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 2,
    },
    manaValue: 3,
    typeLine: "Creature — Human Soldier",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Human", "Soldier"],
    colors: ["W"],
    colorIdentity: ["W"],
    power: 3,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Soldier",
      },
      powerDelta: 1,
      toughnessDelta: 0,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper"],
  },
  {
    identity: "d513e5df-31b0-4756-bf47-403460d0068e",
    sourceVersion: "dfd9b61c07784f9651515359dad517bd0c20236a58d00ddfd668afbeb49d1648",
    sourceOrdinal: 32097,
    rawRecordHash: "7cf351b18f7c24e821dcbc8102527a90a6da593ad1e01f357f62717e4195f224",
    name: "Battle Sliver",
    oracleText: "Sliver creatures you control get +2/+0.",
    manaCost: "{4}{R}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 1,
      G: 0,
      C: 0,
      generic: 4,
    },
    manaValue: 5,
    typeLine: "Creature — Sliver",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Sliver"],
    colors: ["R"],
    colorIdentity: ["R"],
    power: 3,
    toughness: 3,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "subtype",
        subtype: "Sliver",
      },
      powerDelta: 2,
      toughnessDelta: 0,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "d561dcff-0a19-46ac-9dee-f374c840d532",
    sourceVersion: "77c8dbebcda1938b64732ef60c31c9d0994428606afaa31b603509259e530a1f",
    sourceOrdinal: 32143,
    rawRecordHash: "c59b7d9edf9180a63eefa5c2c116ba73092d8a42e32bbbfb754187e5a4b899fa",
    name: "Arvad the Cursed",
    oracleText: "Deathtouch, lifelink\nOther legendary creatures you control get +2/+2.",
    manaCost: "{3}{W}{B}",
    cost: {
      W: 1,
      U: 0,
      B: 1,
      R: 0,
      G: 0,
      C: 0,
      generic: 3,
    },
    manaValue: 5,
    typeLine: "Legendary Creature — Vampire Knight",
    types: ["Creature"],
    supertypes: ["Legendary"],
    subtypes: ["Vampire", "Knight"],
    colors: ["B", "W"],
    colorIdentity: ["B", "W"],
    power: 3,
    toughness: 3,
    oracleKeywords: ["Lifelink", "Deathtouch"],
    intrinsicKeywords: ["deathtouch", "lifelink"],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "legendary",
      },
      powerDelta: 2,
      toughnessDelta: 2,
      layer: "7c",
    },
    commanderEligible: true,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "d72b8254-3df8-431b-955a-ec2aea493e2b",
    sourceVersion: "325155dd5ca833941b67eb256934f061f4fac21374c3436a8e0e5675ce6e2611",
    sourceOrdinal: 32422,
    rawRecordHash: "e270c91924b67e85911fd9b40147edfae79a5a957367cbbd44d67ab19b97a3ad",
    name: "Bladestitched Skaab",
    oracleText: "Other Zombies you control get +1/+0.",
    manaCost: "{U}{B}",
    cost: {
      W: 0,
      U: 1,
      B: 1,
      R: 0,
      G: 0,
      C: 0,
      generic: 0,
    },
    manaValue: 2,
    typeLine: "Creature — Zombie Soldier",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Zombie", "Soldier"],
    colors: ["B", "U"],
    colorIdentity: ["B", "U"],
    power: 2,
    toughness: 3,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Zombie",
      },
      powerDelta: 1,
      toughnessDelta: 0,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "e3886fe8-9b76-4613-8891-4ec74657c087",
    sourceVersion: "8161e8062cd8a482a5fd63895f5ccdf64804da1e13ce5714e683434b5432ce6f",
    sourceOrdinal: 34262,
    rawRecordHash: "3d8cb8356b20d8d7e1ace782d458a910ebd7c5a75c45f12ebaa77a693b0533d6",
    name: "Glorious Anthem",
    oracleText: "Creatures you control get +1/+1.",
    manaCost: "{1}{W}{W}",
    cost: {
      W: 2,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 1,
    },
    manaValue: 3,
    typeLine: "Enchantment",
    types: ["Enchantment"],
    supertypes: [],
    subtypes: [],
    colors: ["W"],
    colorIdentity: ["W"],
    power: null,
    toughness: null,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "all",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["arena", "paper", "mtgo"],
  },
  {
    identity: "f1d8e9a6-1903-4be5-8609-1009a463f393",
    sourceVersion: "59c5807de60aba3f4980de35ab82d5d2d428e4cdfa5820535e2de0f4a42fac1d",
    sourceOrdinal: 36494,
    rawRecordHash: "e8ede106f605b7c272a208e5cadbce0b93ff96bc62c8d31f3a575dd3a9ade721",
    name: "Anthem of Champions",
    oracleText: "Creatures you control get +1/+1.",
    manaCost: "{G}{W}",
    cost: {
      W: 1,
      U: 0,
      B: 0,
      R: 0,
      G: 1,
      C: 0,
      generic: 0,
    },
    manaValue: 2,
    typeLine: "Enchantment",
    types: ["Enchantment"],
    supertypes: [],
    subtypes: [],
    colors: ["G", "W"],
    colorIdentity: ["G", "W"],
    power: null,
    toughness: null,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "all",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "arena", "mtgo"],
  },
  {
    identity: "f43d1ea5-8127-4b64-a87b-ee5cc9b9e9fa",
    sourceVersion: "e2623598858401ca6ede327eefdcd68afe104c5c0ff15f914ec65308d339c4f4",
    sourceOrdinal: 36856,
    rawRecordHash: "34c3baf77d80fb7a84d59522690f8ae4546a3b0956a863326352a7bb7132ade1",
    name: "Squirrel Sovereign",
    oracleText: "Other Squirrels you control get +1/+1.",
    manaCost: "{1}{G}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 0,
      G: 1,
      C: 0,
      generic: 1,
    },
    manaValue: 2,
    typeLine: "Creature — Squirrel Noble",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Squirrel", "Noble"],
    colors: ["G"],
    colorIdentity: ["G"],
    power: 2,
    toughness: 2,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Squirrel",
      },
      powerDelta: 1,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo"],
  },
  {
    identity: "fcb34e92-f991-401c-a494-c2919083bf9e",
    sourceVersion: "90b579392c5652450ce040bc387a49e917fee34c2bfe6d642fbe6d5839e093da",
    sourceOrdinal: 38128,
    rawRecordHash: "8b5a2d92328aa57d31f981ced89d2c2f7b36ca62b277e16a2f5615b6061d67ac",
    name: "Veteran Armorsmith",
    oracleText: "Other Soldier creatures you control get +0/+1.",
    manaCost: "{W}{W}",
    cost: {
      W: 2,
      U: 0,
      B: 0,
      R: 0,
      G: 0,
      C: 0,
      generic: 0,
    },
    manaValue: 2,
    typeLine: "Creature — Human Soldier",
    types: ["Creature"],
    supertypes: [],
    subtypes: ["Human", "Soldier"],
    colors: ["W"],
    colorIdentity: ["W"],
    power: 2,
    toughness: 3,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: true,
      predicate: {
        kind: "subtype",
        subtype: "Soldier",
      },
      powerDelta: 0,
      toughnessDelta: 1,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper"],
  },
  {
    identity: "fed58ccc-db56-4094-8b56-bd29b00e9327",
    sourceVersion: "87328f02982259df1c727feba4af5a0ad46cc17054635601b983f13d79b2e0f1",
    sourceOrdinal: 38455,
    rawRecordHash: "097659bbf1d73ebd8165623d03c94741cd11289298b198393f7a92a6b3a24edd",
    name: "Power Boost",
    oracleText: "Creatures you control get +1/+0.",
    manaCost: "{2}{R}",
    cost: {
      W: 0,
      U: 0,
      B: 0,
      R: 1,
      G: 0,
      C: 0,
      generic: 2,
    },
    manaValue: 3,
    typeLine: "Enchantment",
    types: ["Enchantment"],
    supertypes: [],
    subtypes: [],
    colors: ["R"],
    colorIdentity: ["R"],
    power: null,
    toughness: null,
    oracleKeywords: [],
    intrinsicKeywords: [],
    staticProgram: {
      schema: "static-creature-bonus/1",
      kind: "static-creature-bonus",
      activeZone: "battlefield",
      controller: "source-current",
      excludeSource: false,
      predicate: {
        kind: "all",
      },
      powerDelta: 1,
      toughnessDelta: 0,
      layer: "7c",
    },
    commanderEligible: false,
    digital: false,
    games: ["paper", "mtgo", "arena"],
  },
];
const keywordRules: Partial<Record<Keyword, string>> = {
  flying: "702.9",
  flash: "702.8",
  vigilance: "702.20",
  deathtouch: "702.2",
  lifelink: "702.15",
};
function definitionFor(recipe: StaticBonusPermanentSource): CardDefinition {
  const creature = recipe.types.includes("Creature");
  const rules = [
    ...STATIC_BONUS_RULES,
    ...(creature ? ["302.1", "208.1"] : ["303.1", "303.2"]),
    ...recipe.intrinsicKeywords.map((keyword) => {
      const rule = keywordRules[keyword];
      if (!rule) throw new Error(`Unreviewed intrinsic static-source keyword: ${keyword}`);
      return rule;
    }),
    ...(recipe.commanderEligible ? ["903.3"] : []),
  ];
  return CardDefinition.parse({
    id: `oracle:${recipe.identity}`,
    oracleId: recipe.identity,
    sourceVersion: recipe.sourceVersion,
    name: recipe.name,
    typeLine: recipe.typeLine,
    types: recipe.types,
    subtypes: recipe.subtypes,
    supertypes: recipe.supertypes,
    colors: recipe.colors,
    colorIdentity: recipe.colorIdentity,
    manaCost: recipe.cost,
    manaValue: recipe.manaValue,
    power: recipe.power,
    toughness: recipe.toughness,
    keywords: recipe.intrinsicKeywords,
    manaAbilities: [],
    oracleText: recipe.oracleText,
    commanderEligible: recipe.commanderEligible,
    deckLimit: 1,
    obligations: [...new Set(rules)].map((rule) => `rule:${rule}`),
    implementationRevision: STATIC_BONUS_VERSION,
    staticPrograms: [StaticCreatureBonus.parse(recipe.staticProgram)],
  });
}
function sourceFacts(card: CatalogCard) {
  const o = card.oracle;
  return {
    name: o.name,
    oracleText: o.oracle_text ?? null,
    manaCost: o.mana_cost ?? null,
    manaValue: o.cmc ?? null,
    typeLine: o.type_line ?? null,
    colors: o.colors ?? null,
    colorIdentity: o.color_identity,
    power: o.power ?? null,
    toughness: o.toughness ?? null,
    oracleKeywords: o.keywords,
    digital: o.digital ?? null,
    games: o.games,
  };
}
function expectedFacts(recipe: StaticBonusPermanentSource) {
  return {
    name: recipe.name,
    oracleText: recipe.oracleText,
    manaCost: recipe.manaCost,
    manaValue: recipe.manaValue,
    typeLine: recipe.typeLine,
    colors: recipe.colors,
    colorIdentity: recipe.colorIdentity,
    power: recipe.power === null ? null : String(recipe.power),
    toughness: recipe.toughness === null ? null : String(recipe.toughness),
    oracleKeywords: recipe.oracleKeywords,
    digital: recipe.digital,
    games: recipe.games,
  };
}
export function bindStaticBonusPermanent(card: CatalogCard): CardDefinition | null {
  const recipe = STATIC_BONUS_PERMANENTS.find((row) => row.identity === card.identity);
  if (!recipe) return null;
  const o = card.oracle;
  if (
    !card.eligibility.some((row) => row.role === "main-deck" && row.status === "candidate") ||
    card.versionHash !== recipe.sourceVersion ||
    card.sourceOrdinal !== recipe.sourceOrdinal ||
    card.sourceArchiveHash !== STATIC_BONUS_ARCHIVE ||
    card.bundleHash !== STATIC_BONUS_SOURCE_BUNDLE ||
    o.oracle_id !== recipe.identity ||
    o.layout !== "normal" ||
    o.card_faces !== undefined ||
    o.loyalty !== undefined ||
    o.defense !== undefined ||
    o.hand_modifier !== undefined ||
    o.life_modifier !== undefined ||
    o.color_indicator !== undefined ||
    o.legalities.commander !== "legal" ||
    (recipe.power === null && (o.power !== undefined || o.toughness !== undefined)) ||
    canonicalJson(sourceFacts(card)) !== canonicalJson(expectedFacts(recipe))
  )
    return null;
  return definitionFor(recipe);
}
/** Exact reconstruction rejects erased programs and altered predicates, costs or intrinsic abilities. */
export function reviewedStaticBonusDefinition(definition: CardDefinition): boolean {
  const recipe = STATIC_BONUS_PERMANENTS.find((row) => row.identity === definition.oracleId);
  return recipe !== undefined && canonicalJson(definitionFor(recipe)) === canonicalJson(definition);
}
