import { createHash } from "node:crypto";
import {
  access,
  cp,
  mkdir,
  mkdtemp,
  readdir,
  readFile,
  rename,
  rm,
  stat,
  writeFile,
} from "node:fs/promises";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";
import { XR_ASSET_PACKAGE_VERSION, XR_PROFILE_IDS } from "../app/game/scene/xr-assets.ts";

const appRoot = fileURLToPath(new URL("..", import.meta.url));
const packageRoot = dirname(
  fileURLToPath(import.meta.resolve("@webxr-input-profiles/assets/package.json")),
);
const packageInfo = JSON.parse(await readFile(join(packageRoot, "package.json"), "utf8")) as {
  version: string;
};
if (packageInfo.version !== XR_ASSET_PACKAGE_VERSION) {
  throw new Error(
    `XR assets require the tested ${XR_ASSET_PACKAGE_VERSION} package, received ${packageInfo.version}.`,
  );
}
const publicRoot = join(appRoot, "public");
const target = join(publicRoot, "xr-profiles");
const lock = join(publicRoot, ".xr-assets-lock");
const marker = ".generated-webxr-profiles";
await mkdir(publicRoot, { recursive: true });
let locked = false;
for (let attempt = 0; attempt < 400; attempt += 1) {
  try {
    await mkdir(lock);
    locked = true;
    break;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "EEXIST") throw error;
    await Bun.sleep(25);
  }
}
if (!locked) throw new Error("XR asset synchronization is already running; retry shortly.");
let staging: string | undefined;
try {
  staging = await mkdtemp(join(publicRoot, ".xr-assets-"));
  for (const profile of XR_PROFILE_IDS) {
    await cp(join(packageRoot, "dist/profiles", profile), join(staging, profile), {
      recursive: true,
      errorOnExist: true,
      force: false,
    });
  }
  await cp(join(packageRoot, "LICENSE.md"), join(staging, "LICENSE.md"));
  await cp(join(packageRoot, "README.md"), join(staging, "SOURCE-README.md"));
  const files: Array<{ path: string; bytes: number; sha256: string }> = [];
  async function inventory(path: string): Promise<void> {
    for (const entry of (await readdir(path, { withFileTypes: true })).sort((a, b) =>
      a.name.localeCompare(b.name),
    )) {
      const absolute = join(path, entry.name);
      if (entry.isDirectory()) await inventory(absolute);
      else {
        const data = await readFile(absolute);
        files.push({
          path: relative(staging ?? "", absolute).replaceAll("\\", "/"),
          bytes: data.byteLength,
          sha256: createHash("sha256").update(data).digest("hex"),
        });
      }
    }
  }
  await inventory(staging);
  // Every required controller needs both hands; tiny/missing GLBs indicate a broken package copy.
  for (const profile of XR_PROFILE_IDS) {
    for (const side of ["left", "right"]) {
      const metadata = await stat(join(staging, profile, `${side}.glb`));
      if (metadata.size < 20)
        throw new Error(`Missing or invalid XR controller asset: ${profile}/${side}.glb`);
    }
  }
  await writeFile(
    join(staging, "manifest.json"),
    `${JSON.stringify(
      {
        package: "@webxr-input-profiles/assets",
        version: packageInfo.version,
        profiles: XR_PROFILE_IDS,
        files,
      },
      null,
      2,
    )}\n`,
  );
  await writeFile(join(staging, marker), "Generated by sync-xr-assets.ts; safe to regenerate.\n");
  try {
    await access(target);
    await access(join(target, marker));
    await rm(target, { recursive: true });
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
    // Refuse an existing unmarked directory, even when it contains no files.
    try {
      await access(target);
      throw new Error(
        "public/xr-profiles exists without the generator ownership marker; move it before synchronizing.",
      );
    } catch (checkError) {
      if ((checkError as NodeJS.ErrnoException).code !== "ENOENT") throw checkError;
    }
  }
  await rename(staging, target);
  staging = undefined;
  console.info(
    `Prepared ${XR_PROFILE_IDS.length} local XR profiles (${files.length} files) from assets ${packageInfo.version}.`,
  );
} finally {
  if (staging) await rm(staging, { recursive: true, force: true });
  await rm(lock, { recursive: true, force: true });
}
