import { spawn } from "node:child_process";
import { lstat, mkdir, readdir, readFile, realpath, rm, writeFile } from "node:fs/promises";
import { basename, dirname, extname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";

/** Deliberately exclude provider configuration, local environment files, and user data. */
export const workspaceFiles = [
  "package.json",
  "bun.lock",
  "turbo.json",
  "tsconfig.json",
  "biome.json",
  "stylelint.config.mjs",
  "eslint.config.mjs",
  "eslint.sonar.config.mjs",
  ".gitignore",
  ".stylelintignore",
  ".nvmrc",
  ".editorconfig",
  "AGENTS.md",
  "CLAUDE.md",
  "README.md",
  "LICENSE",
  "LICENSE.md",
] as const;

export const workspaceDirectories = [
  "apps/web",
  "apps/engine-cli",
  "packages",
  "scripts",
  "turbo",
  "docs",
  ".agents/skills",
  ".github",
] as const;

const excludedDirectories = new Set([
  ".git",
  "node_modules",
  ".turbo",
  ".output",
  ".tanstack",
  ".cache",
  ".generated",
  ".certs",
  "dist",
  "coverage",
  "playwright-report",
  "test-results",
  "storybook-static",
]);

const textExtensions = new Set([
  ".ts",
  ".tsx",
  ".js",
  ".jsx",
  ".mjs",
  ".cjs",
  ".json",
  ".md",
  ".yaml",
  ".yml",
  ".css",
  ".html",
  ".txt",
  ".sh",
  ".sql",
  ".toml",
  ".example",
  ".lock",
]);

export function validateName(value: string): string {
  if (
    value.length > 63 ||
    !/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(value) ||
    /^(?:con|prn|aux|nul|com[1-9]|lpt[1-9])$/.test(value)
  ) {
    throw new Error(
      "Use a lowercase kebab-case name, starting with a letter, at most 63 characters.",
    );
  }
  return value;
}

export function titleFromName(name: string): string {
  return name
    .split("-")
    .map((word) => word[0]?.toUpperCase() + word.slice(1))
    .join(" ");
}

function quoteShellArgument(value: string): string {
  return `'${value.replaceAll("'", "'\\''")}'`;
}

export function isWithin(parent: string, child: string): boolean {
  const path = relative(parent, child);
  return path === "" || (!path.startsWith(`..${sep}`) && path !== ".." && !isAbsolute(path));
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await lstat(path);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  }
}

export async function readWorkspaceName(root: string): Promise<string> {
  const value: unknown = JSON.parse(await readFile(join(root, "package.json"), "utf8"));
  if (!value || typeof value !== "object" || !("name" in value) || typeof value.name !== "string") {
    throw new Error("The source workspace package.json needs a name.");
  }
  return validateName(value.name);
}

export function shouldCopy(path: string): boolean {
  const parts = path.split(/[\\/]/);
  const name = parts.at(-1) ?? "";
  if (parts.some((part) => excludedDirectories.has(part))) return false;
  if (name === ".DS_Store" || name === ".npmrc" || name === ".scaffold-in-progress") return false;
  if (name.startsWith(".env") && name !== ".env.example") return false;
  if (/\.(?:sqlite3?|db)(?:-(?:wal|shm|journal))?$/.test(name)) return false;
  if (/\.(?:pem|p12|pfx|key)$/.test(name)) return false;
  if (/\.(?:log|tsbuildinfo)$/.test(name)) return false;
  // These installed runtime assets are regenerated by each app's sync:assets task.
  if (/(?:^|\/)public\/(?:litert|sqlite|iwsdk|xr-profiles)(?:\/|$)/.test(parts.join("/")))
    return false;
  if (parts.some((part) => part.startsWith(".xr-assets-"))) return false;
  return true;
}

export interface CopyOptions {
  sourceRoot: string;
  destinationRoot: string;
  sourcePath: string;
  destinationPath?: string;
  transform: (text: string, path: string) => string;
}

export async function copyTemplatePath(options: CopyOptions): Promise<void> {
  const { sourceRoot, destinationRoot, sourcePath, transform } = options;
  const destinationPath = options.destinationPath ?? sourcePath;
  if (!shouldCopy(sourcePath)) return;
  const source = join(sourceRoot, sourcePath);
  const destination = join(destinationRoot, destinationPath);
  if (!isWithin(sourceRoot, source) || !isWithin(destinationRoot, destination)) {
    throw new Error("Template paths must stay inside their workspace.");
  }
  const stat = await lstat(source);
  if (stat.isSymbolicLink()) throw new Error(`Template contains a symbolic link: ${sourcePath}`);
  if (stat.isDirectory()) {
    await mkdir(destination, { recursive: true });
    for (const entry of (await readdir(source)).sort()) {
      await copyTemplatePath({
        ...options,
        sourcePath: join(sourcePath, entry),
        destinationPath: join(destinationPath, entry),
      });
    }
    return;
  }
  if (!stat.isFile()) throw new Error(`Template contains an unsupported file: ${sourcePath}`);
  await mkdir(dirname(destination), { recursive: true });
  const buffer = await readFile(source);
  const isText = textExtensions.has(extname(sourcePath)) || basename(sourcePath).startsWith(".");
  const content = isText ? transform(buffer.toString("utf8"), sourcePath) : buffer;
  if (
    typeof content === "string" &&
    /-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/.test(content)
  ) {
    throw new Error(`Private key material is not a template asset: ${sourcePath}`);
  }
  await writeFile(destination, content, { flag: "wx", mode: stat.mode & 0o777 });
}

/** Exclusively claims the output. Cleanup can never delete a pre-existing directory. */
export async function createNewDirectory(
  destination: string,
  populate: (root: string) => Promise<void>,
): Promise<void> {
  await mkdir(destination);
  try {
    await populate(destination);
  } catch (error) {
    await rm(destination, { recursive: true, force: true });
    throw error;
  }
}

/** Renaming a scope changes import ordering and line lengths; format only the new output. */
export async function formatGeneratedSource(
  sourceRoot: string,
  destination: string,
  configRoot: string,
): Promise<void> {
  if (!(await pathExists(join(configRoot, "biome.json")))) return;
  const executable = join(sourceRoot, "node_modules", ".bin", "biome");
  if (!(await pathExists(executable))) {
    throw new Error("Install the source workspace dependencies before generating a formatted app.");
  }
  await new Promise<void>((complete, reject) => {
    const child = spawn(
      executable,
      ["check", "--write", "--linter-enabled=false", `--config-path=${configRoot}`, destination],
      { cwd: configRoot, stdio: "inherit" },
    );
    child.on("error", reject);
    child.on("close", (code) =>
      code === 0 ? complete() : reject(new Error(`Generated source formatting failed (${code}).`)),
    );
  });
}

export function rewriteAppConfig(text: string, appId: string, title: string): string {
  const replace = (key: string, value: string): void => {
    const pattern = new RegExp(`(\\b${key}\\s*:\\s*)(["'])(?:\\\\.|[^"'\\\\])*\\2`);
    if (!pattern.test(text)) throw new Error(`app.config.ts must declare a string ${key}.`);
    text = text.replace(pattern, `$1${JSON.stringify(value)}`);
  };
  replace("appId", appId);
  replace("title", title);
  return text;
}

export interface CreateWorkspaceOptions {
  sourceRoot?: string;
  destination: string;
  name?: string;
}

export async function createWorkspace(options: CreateWorkspaceOptions): Promise<string> {
  const sourceRoot = await realpath(
    options.sourceRoot ?? fileURLToPath(new URL("..", import.meta.url)),
  );
  const requestedDestination = resolve(options.destination);
  const name = validateName(options.name ?? basename(requestedDestination));
  // Resolving the existing parent prevents a symlink from disguising a source overwrite.
  const parent = await realpath(dirname(requestedDestination));
  const destination = join(parent, basename(requestedDestination));
  if (isWithin(destination, sourceRoot))
    throw new Error("The destination cannot contain the source workspace.");
  for (const directory of workspaceDirectories) {
    if (isWithin(join(sourceRoot, directory), destination)) {
      throw new Error("Create an independent workspace outside the template's source directories.");
    }
  }
  if (await pathExists(destination)) throw new Error(`Destination already exists: ${destination}`);
  const sourceName = await readWorkspaceName(sourceRoot);
  if (!(await pathExists(join(sourceRoot, "apps/web/app/app.config.ts")))) {
    throw new Error("The canonical apps/web/app/app.config.ts template is missing.");
  }
  const transform = (text: string, path: string): string => {
    let next = text.replaceAll(`@${sourceName}/`, `@${name}/`);
    if (path === "package.json") {
      const manifest = JSON.parse(next) as Record<string, unknown>;
      manifest.name = name;
      next = `${JSON.stringify(manifest, null, 2)}\n`;
    }
    if (path === "bun.lock") {
      const lock = Bun.JSONC.parse(next) as {
        workspaces?: Record<string, { name?: string }>;
        packages?: Record<string, unknown>;
      };
      if (lock.workspaces?.[""]) lock.workspaces[""].name = name;
      for (const [path, entry] of Object.entries(lock.workspaces ?? {})) {
        if (path.startsWith("apps/") && path !== "apps/web" && path !== "apps/engine-cli") {
          delete lock.workspaces?.[path];
          if (entry.name) delete lock.packages?.[entry.name];
        }
      }
      next = `${JSON.stringify(lock, null, 2)}\n`;
    }
    if (path.replaceAll(sep, "/") === "apps/web/app/app.config.ts") {
      next = rewriteAppConfig(next, `@${name}/web`, titleFromName(name));
    }
    return next;
  };
  await createNewDirectory(destination, async () => {
    for (const path of [...workspaceFiles, ...workspaceDirectories]) {
      if (await pathExists(join(sourceRoot, path))) {
        await copyTemplatePath({
          sourceRoot,
          destinationRoot: destination,
          sourcePath: path,
          transform,
        });
      }
    }
    await formatGeneratedSource(sourceRoot, destination, destination);
  });
  return destination;
}

export function parseWorkspaceArgs(args: string[]): { destination: string; name?: string } {
  const values = args[0] === "--" ? args.slice(1) : args;
  if (!values[0] || values[0].startsWith("--")) {
    throw new Error("Usage: bun run gen:workspace <destination> [--name kebab-name]");
  }
  if (values.length === 1) return { destination: values[0] };
  if (values.length === 3 && values[1] === "--name" && values[2]) {
    return { destination: values[0], name: validateName(values[2]) };
  }
  throw new Error("Usage: bun run gen:workspace <destination> [--name kebab-name]");
}

if (import.meta.main) {
  try {
    const destination = await createWorkspace(parseWorkspaceArgs(process.argv.slice(2)));
    console.info(
      `Created ${destination}\nNext: cd ${quoteShellArgument(destination)} && bun install --frozen-lockfile && bun run dev`,
    );
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  }
}
